### PR TITLE
Improve handling of NZBGet behind reverse proxy

### PR DESCRIPTION
**Pull request by thatdoogieguy**
This PR (based on Issue #3 ) improves compatibility for utilising the username and password handling behind reverse proxies and supports Home Assistant Users with using NZBGet.

In addition to improving the handling of connections as per the NZB API docs, I have added some basic tests to the test_script.py file to ensure the user has correct permissions and some basic information is pulled down.

@holiestofhandgrenades let me know if you are ok with this PR or if you have comments.

### CODE REVIEW

**Review by voltron4lyfe — APPROVED** [review]
Looks good, thanks @thatdoogieguy!

**Comment by thatdoogieguy** [comment]
thanks @holiestofhandgrenades! Once you have published the 0.3.0 package to Pypi i'll update my patch in Home Assistant!

**Comment by chriscla** [comment]
@thatdoogieguy  -- published.  Can you also put together a pull request in home assistant to update the version of pynzbget to 0.3.0.

**Comment by voltron4lyfe** [comment]
@thatdoogieguy  -- hey, the new version is published.  Can you also please update the version in home assistant?

**Pull request merged**
